###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    #PHP Service
    php-fpm:

      build: phpdocker/php-fpm
      container_name: testing-package-php
      restart: unless-stopped
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"

    #MySQL Service
    db:
      image: mysql:5.7
      container_name: testing-package-mysql
      restart: unless-stopped
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "3306:3306"

    #Nginx Service
    webserver:
      image: nginx:alpine
      container_name: testing-package-webserver
      restart: unless-stopped
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
       - "443:443"

    adminer:
      image: adminer
      container_name: testing-package-adminer
      restart: unless-stopped
      ports:
        - "8080:8080"

